### PR TITLE
stb_vorbis: fix interleaved appends silence at end

### LINKED ISSUE #92: Decoding a particular OGG file appends a bit of silence at the end
There's a problem with decoding a particular 48 kHz OGG file: SDL_Sound appears to append a small bit of silence at the end (around 5-6 ms). This would not be a concern if a sound would play once, but when looping this extra bit causes an audible crackling noise.

Decoding is done *without any requested conversion*, passing `null` as desired format parameter.

If I convert the file itself to 44100 Hz, then it is loaded fine, without extra appends.

The original file:
[VacuumNoise.zip](https://github.com/icculus/SDL_sound/files/13519742/VacuumNoise.zip)

I used a small program to write SDL_Decode results to a file "raw". This "raw" file may be imported in a software like "Audacity", and a trailing silence observed:
[test.raw.zip](https://github.com/icculus/SDL_sound/files/13519761/test.raw.zip)
Properties: 32-bit float, 48 kHz, 2 Channels, Little-endian.

<details>
<summary>The code used to decode and write this file is under the spoiler.</summary>

```
#include <stdio.h>
#include <SDL.h>
#include <SDL_sound.h>

const size_t SampleDefaultBufferSize = 64 * 1024;

int main(int argc, char *argv[])
{
    Sound_Init();

    Sound_Sample * sample = Sound_NewSampleFromFile("VacuumNoise.ogg", NULL, SampleDefaultBufferSize);
    if (!sample)
        return -1;

    FILE *f = fopen("test.raw", "wb");
    if (!f)
    {
        Sound_FreeSample(sample);
        return -2;
    }

    do
    {
        size_t sz = Sound_Decode(sample);
        if (sz > 0)
        {
            fwrite(sample->buffer, 1, sz, f);
        }
    } while ((sample->flags & SOUND_SAMPLEFLAG_EOF) == 0);

    fclose(f);
    Sound_FreeSample(sample);

    return 0;
}
```
</details>

### PR DESCRIPTION
**Pull request by ericoporto**
fix #92

alternative to #95.

### CODE REVIEW

File: src/stb_vorbis.h [hunk 1]
```diff
@@ -5637,6 +5637,7 @@ int stb_vorbis_get_samples_float_interleaved(stb_vorbis *f, int channels, float
    int len = num_floats / channels;
    int n=0;
    int z = f->channels;
+   unsigned int lgs=stb_vorbis_stream_length_in_samples(f);
```
Comment (sezero) [inline src/stb_vorbis.h:5640]: Can this not be cached during creation ?

Comment (sezero) [reply src/stb_vorbis.h:5640]: OK, ignore me, it is cached..

**Comment by sezero** [comment]
CC: @Wohlstand

**Comment by icculus** [comment]
I'm fine with this; if no one has an objection (@Wohlstand?), let's merge it.

**Comment by icculus** [comment]
We should probably point Sean Barrett at this if it's useful in a general sense to stb_vorbis.

**Comment by sezero** [comment]
> We should also probably point Sean Barrett at this if it's useful in a general sense to stb_vorbis.

`stb_vorbis_stream_length_in_samples` is a [PR](https://github.com/nothings/stb/pull/1295) in stb_vorbis not yet merged. Only thing that can be done with mainstream is that maybe @Wohlstand can amend this to his PR if the patch is correct.

**Comment by ericoporto** [comment]
> `stb_vorbis_stream_length_in_samples` is a [PR](https://github.com/nothings/stb/pull/1295) in stb_vorbis not yet merged

Just for reference, it actually is in [other PR](https://github.com/nothings/stb/pull/1331) that depends on the mentioned PR being merged.

**Comment by sezero** [comment]
To me, this looks fine -- still waiting @Wohlstand to make a comment.

I guess the same change is needed in `stb_vorbis_get_samples_float()` and `stb_vorbis_get_samples_short*()`, no? (Haven't tested..) I'm willing to apply it to my fork after all is cleared (and it will be applied to all users of my fork.)

**Comment by Wohlstand** [comment]
Hello!
I'm not at home yet, yesterday I was very busy, I'll reply as soon as I'll get my home.

**Comment by ericoporto** [comment]
> I guess the same change is needed in `stb_vorbis_get_samples_float()` and `stb_vorbis_get_samples_short*()`, no? (Haven't tested..) I'm willing to apply it to my fork after all is cleared (and it will be applied to all users of my fork.)

I don't have an audio file that causes an issue with those for me to test, would have to come up with something in Audacity for this, the one in the issue was from the user of ags that noticed the issue and reported.

**Comment by Wohlstand** [comment]
> To me, this looks fine -- still waiting @Wohlstand to make a comment.
> 
> I guess the same change is needed in `stb_vorbis_get_samples_float()` and `stb_vorbis_get_samples_short*()`, no? (Haven't tested..) I'm willing to apply it to my fork after all is cleared (and it will be applied to all users of my fork.)

Yea, I took a small look, and ye, as you said, the change is needed not just in one interleaved function: this problem exists in all other functions too. Mainstream Mixer as well as my MixerX fork doesn't use interleaved function (except of my experimental "turn into multi-track" feature to interpret extra channels as stereo/mono/etc. concurrent tracks with ability to mute each of them), and I guess, somebody reported this problem at the Mixer too, or I confuse some :thinking:

**Comment by Wohlstand** [comment]
Also, pay attention that `stb_vorbis_stream_length_in_samples` function may return the `SAMPLE_unknown` (which is -1), or 0 (when any error ocurrs), so, be careful!

File: src/stb_vorbis.h [hunk 2]
```diff
@@ -5656,6 +5657,11 @@ int stb_vorbis_get_samples_float_interleaved(stb_vorbis *f, int channels, float
          break;
    }
    f->current_playback_loc += n;
+   if(f->current_playback_loc > lgs) {
```
Comment (Wohlstand) [inline src/stb_vorbis.h:5660]: Please check for the `lgs >= 0`, otherwise, it may return 0 (on any error) or -1 when it has an invalid duration value.

Comment (ericoporto) [reply src/stb_vorbis.h]: added a `&& lgs >= 0` for checking it

Comment (ericoporto) [reply src/stb_vorbis.h]: Wait a minute, the return value should be positive as is an unsigned int, how could it be `-1`?

Comment (ericoporto) [reply src/stb_vorbis.h]: I read the code and "1 when it has an invalid duration value" doesn't exist, it can only be 0.

Comment (Wohlstand) [reply src/stb_vorbis.h]: It CAN return -1, because of:
```
#define SAMPLE_unknown  0xffffffff
```
when it's a signed 32-bit integer, it's `-1`.

Comment (ericoporto) [reply src/stb_vorbis.h]: There's an if before return that makes it zero, no?

Comment (ericoporto) [reply src/stb_vorbis.h]: Well added an extra check for lgs, but lgs gets it's value from `stb_vorbis_stream_length_in_samples`, the `-1` can only happen in other things... This code is a bit terrible because it mixes the `SAMPLE_unknown` definition, the `-1`, the direct `0xffffffff`... And I have no idea what the value it will be once it changes to 64 bit. `UINT_MAX` looks easier to understand.

Comment (Wohlstand) [reply src/stb_vorbis.h]: On my end of the fork, I already replaced all the offsets from int into int64_t (otherwise it won't allow play large files, longer than 5 hours, and also depending on the sample rate), and the value of `SAMPLE_unknown` I simply replaced with `-1`: simple and easy.: https://github.com/WohlSoft/SDL-Mixer-X/blob/master/src/codecs/stb_vorbis/stb_vorbis.h

Comment (Wohlstand) [reply src/stb_vorbis.h]: > SAMPLE_unknown

Why not to just use the `SAMPLE_unknown` value directly?

File: src/stb_vorbis.h [hunk 3]
```diff
@@ -5656,6 +5657,11 @@ int stb_vorbis_get_samples_float_interleaved(stb_vorbis *f, int channels, float
          break;
    }
    f->current_playback_loc += n;
+   if(f->current_playback_loc > lgs && lgs > 0 && lgs != UINT_MAX) {
```
Comment (Wohlstand) [inline src/stb_vorbis.h:5660]: Why not to just use the `SAMPLE_unknown` directly? It's private code, and you are free to use that.
```cpp
if(f->current_playback_loc > lgs && lgs > 0 && lgs != SAMPLE_unknown) {
```

File: src/stb_vorbis.h (hunk 2 above)
Comment (ericoporto) [reply src/stb_vorbis.h]: In your code there is a mix of int64_t and uint64_t, shouldn't it be all uint64_t ? I felt that it would be easier to match the eventual 64-bit upgrade by using an existent constant instead of the current manual 0xf...f.

Comment (ericoporto) [reply src/stb_vorbis.h]: btw, I won't change anything right now because GitHub PR is melting: https://www.githubstatus.com/

Comment (ericoporto) [reply src/stb_vorbis.h]: It appears GitHub is normalizing

File: src/stb_vorbis.h (hunk 3 above)
Comment (ericoporto) [reply src/stb_vorbis.h]: Adjusted as request : https://github.com/icculus/SDL_sound/compare/fef554e25e79aef3dd24fa964e219f9a5b20a309..945fbbe3a09dd1ae043c2a6b02c9e622cd24f346

I stand-by what I said that stb_vorbis using ints directly is terrible and it should use size_t and SIZE_MAX instead or any other regular c type that is appropriate or typedef things to make sense instead of using naked int/uint mixed around...

**Comment by sezero** [comment]
Any changes to `stb_vorbis_get_samples_float_interleaved` must actually
be applied to `stb_vorbis_get_samples_float`, `stb_vorbis_get_samples_short`
and `stb_vorbis_get_samples_short_interleaved` as well.

@ericoporto: Is the following refactored version good? (I build-tested only)
@icculus, @Wohlstand: please review.

```diff
diff --git a/src/stb_vorbis.h b/src/stb_vorbis.h
index 8686bdf..7d2418d 100644
--- a/src/stb_vorbis.h
+++ b/src/stb_vorbis.h
@@ -5512,6 +5512,21 @@ int stb_vorbis_get_frame_short_interleaved(stb_vorbis *f, int num_c, short *buff
    return len;
 }
 
+static int fixup_current_playback_loc(stb_vorbis *f, int n)
+{
+   unsigned int lgs;
+
+   f->current_playback_loc += n;
+   lgs = stb_vorbis_stream_length_in_samples(f);
+   if (f->current_playback_loc > lgs && lgs > 0 && lgs != SAMPLE_unknown) {
+       int r = n - (f->current_playback_loc - (int)lgs);
+       f->current_playback_loc = lgs;
+       return r;
+   }
+
+   return n;
+}
+
 int stb_vorbis_get_samples_short_interleaved(stb_vorbis *f, int channels, short *buffer, int num_shorts)
 {
    float **outputs;
@@ -5528,8 +5543,7 @@ int stb_vorbis_get_samples_short_interleaved(stb_vorbis *f, int channels, short
       if (n == len) break;
       if (!stb_vorbis_get_frame_float(f, NULL, &outputs)) break;
    }
-   f->current_playback_loc += n;
-   return n;
+   return fixup_current_playback_loc(f, n);
 }
 
 int stb_vorbis_get_samples_short(stb_vorbis *f, int channels, short **buffer, int len)
@@ -5546,8 +5560,7 @@ int stb_vorbis_get_samples_short(stb_vorbis *f, int channels, short **buffer, in
       if (n == len) break;
       if (!stb_vorbis_get_frame_float(f, NULL, &outputs)) break;
    }
-   f->current_playback_loc += n;
-   return n;
+   return fixup_current_playback_loc(f, n);
 }
 
 #ifndef STB_VORBIS_NO_STDIO
@@ -5655,8 +5668,7 @@ int stb_vorbis_get_samples_float_interleaved(stb_vorbis *f, int channels, float
       if (!stb_vorbis_get_frame_float(f, NULL, &outputs))
          break;
    }
-   f->current_playback_loc += n;
-   return n;
+   return fixup_current_playback_loc(f, n);
 }
 
 int stb_vorbis_get_samples_float(stb_vorbis *f, int channels, float **buffer, int num_samples)
@@ -5682,8 +5694,7 @@ int stb_vorbis_get_samples_float(stb_vorbis *f, int channels, float **buffer, in
       if (!stb_vorbis_get_frame_float(f, NULL, &outputs))
          break;
    }
-   f->current_playback_loc += n;
-   return n;
+   return fixup_current_playback_loc(f, n);
 }
 #endif // STB_VORBIS_NO_PULLDATA_API
 
```

**Comment by ericoporto** [comment]
@sezero I tested and for the test case of issues I had this does fix it the same.

My test case example I did using my rawdecoder (https://github.com/ericoporto/SDL_sound-1/commit/12fc2961c3cb22e2920b4257b6c4a9edefdcf63a, which requires [this audacity import setting](https://github.com/ericoporto/sdl_sound_issue_92)).

I also tried to listen a few small ogg files I had here (only game sfx, nothing fancy), and it appears to still work fine for them too.

**Comment by sezero** [comment]
> @sezero I tested and for the test case of issues I had this does fix it the same.

Good. Waiting an additional green light from @icculus
(and one from @Wohlstand wouldn't hurt either.)

> My test case example

IIRC it is in #92, yes? Can you attach it here too?
(to make the reviewers' job easier.)

**Comment by ericoporto** [comment]
Sure. Build the rawdecoder from below (or just get this commit https://github.com/ericoporto/SDL_sound-1/commit/12fc2961c3cb22e2920b4257b6c4a9edefdcf63a)

<details>

```c

#ifdef _WIN32
#define SDL_MAIN_HANDLED /* this is a console-only app */
#endif
#include <stdio.h>
#include <SDL.h>
#include <SDL_sound.h>

const size_t SampleDefaultBufferSize = 64 * 1024;

int main(int argc, char *argv[])
{
    Sound_Init();

    Sound_Sample * sample = Sound_NewSampleFromFile("VacuumNoise.ogg", NULL, SampleDefaultBufferSize);
    if (!sample)
        return -1;

    FILE *f = fopen("test.raw", "wb");
    if (!f)
    {
        Sound_FreeSample(sample);
        return -2;
    }

    do
    {
        size_t sz = Sound_Decode(sample);
        if (sz > 0)
        {
            fwrite(sample->buffer, 1, sz, f);
        }
    } while ((sample->flags & SOUND_SAMPLEFLAG_EOF) == 0);

    fclose(f);
    Sound_FreeSample(sample);

    return 0;
}
```

</details>

and run it with [VacuumNoise.ogg.zip](https://github.com/user-attachments/files/18391289/VacuumNoise.ogg.zip) (unzip before). It should generate a `test.raw` file, which can be imported in Audacity using the settings below

image

**Comment by icculus** [comment]
I think this has lived here long enough. If there are other problems, open a new bug report.  :)

**Comment by sezero** [comment]
I guess we should apply this to SDL_mixer, yes?

**Comment by sezero** [comment]
> I guess we should apply this to SDL_mixer, yes?

.. and done.
